### ISSUE TITLE
Versions of node and npm to use?

### ISSUE THREAD

**Issue by taylorsilva** [molly/static-timeline-generator#2]
Sorry if this is a silly question. I'm not well versed in the node and npm communities.

I'm getting errors when running `npm install`. After some searching it seems to be related to the `node-sass` dependency and my version of node. I initially installed node 17. I've installed node 16 and am trying again to run `npm install`. I'm going to keep downgrading until node 10 before giving up. Will share my results here. If anyone has any tips or suggestions as to what I should try please share ❤️

**Comment by taylorsilva** [comment]
Logs from install with node 16

<details>
  <summary>Click to expand!</summary>
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile node-sass: No matching version found for node-sass@1.44.0.
npm WARN old lockfile     at module.exports (/usr/local/Cellar/node@16/16.14.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/Cellar/node@16/16.14.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/Cellar/node@16/16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:743:9)
npm WARN old lockfile  Could not fetch metadata for node-sass@1.44.0 node-sass: No matching version found for node-sass@1.44.0.
npm WARN old lockfile     at module.exports (/usr/local/Cellar/node@16/16.14.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/Cellar/node@16/16.14.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/Cellar/node@16/16.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:743:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.44.0',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.2.0',        '0.2.1',         '0.2.2',        '0.2.3',
npm WARN old lockfile     '0.2.4',        '0.2.5',         '0.2.6',        '0.3.0',
npm WARN old lockfile     '0.4.0',        '0.4.1',         '0.4.2',        '0.4.3',
npm WARN old lockfile     '0.4.4',        '0.5.0',         '0.5.1',        '0.5.2',
npm WARN old lockfile     '0.5.3',        '0.5.4',         '0.6.0',        '0.6.1',
npm WARN old lockfile     '0.6.2',        '0.6.3',         '0.6.4',        '0.6.5',
npm WARN old lockfile     '0.6.6',        '0.6.7',         '0.7.0-alpha',  '0.7.0',
npm WARN old lockfile     '0.8.0',        '0.8.1',         '0.8.2',        '0.8.3',
npm WARN old lockfile     '0.8.4',        '0.8.5',         '0.8.6',        '0.9.0',
npm WARN old lockfile     '0.9.1',        '0.9.2',         '0.9.3',        '0.9.4-rc1',
npm WARN old lockfile     '0.9.4',        '0.9.5-rc1',     '0.9.5',        '0.9.6',
npm WARN old lockfile     '1.0.0',        '1.0.1',         '1.0.2-alpha',  '1.0.2',
npm WARN old lockfile     '1.0.3',        '1.1.0',         '1.1.1',        '1.1.2',
npm WARN old lockfile     '1.1.3',        '1.1.4',         '1.2.0',        '1.2.1',
npm WARN old lockfile     '1.2.2',        '1.2.3',         '2.0.0-beta',   '2.0.0',
npm WARN old lockfile     '2.0.1',        '3.0.0-alpha.0', '3.0.0-beta.2', '3.0.0-beta.3',
npm WARN old lockfile     '3.0.0-beta.4', '2.1.0',         '2.1.1',        '3.0.0-beta.5',
npm WARN old lockfile     '3.0.0-beta.7', '3.0.0',         '3.1.0',        '3.1.1',
npm WARN old lockfile     '3.1.2',        '3.2.0',         '3.3.0',        '3.3.1',
npm WARN old lockfile     '3.3.2',        '3.3.3',         '3.4.0-beta1',  '3.4.0-beta.2',
npm WARN old lockfile     '3.4.0',        '3.4.1',         '3.4.2',        '3.5.0-beta.1',
npm WARN old lockfile     '3.5.1',        '3.5.2',         '3.5.3',        '3.6.0',
npm WARN old lockfile     '3.7.0',        '3.8.0',         '3.9.0',        '3.9.1',
npm WARN old lockfile     '3.9.2',        '3.9.3',         '3.10.0',       '3.10.0-1',
npm WARN old lockfile     '3.10.1',       '3.11.0',        '3.11.1',       '3.11.2',
npm WARN old lockfile     ... 44 more items
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '7.0.1', next: '4.8.3', beta: '4.11.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /Users/taylor/workspace/static-timeline-generator/node_modules/gulp-sass/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/Cellar/node@16/16.14.0/bin/node /Users/taylor/workspace/static-timeline-generator/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR!   c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.5"' -I/Users/taylor/.node-gyp/16.14.0/include/node -I/Users/taylor/.node-gyp/16.14.0/src -I/Users/taylor/.node-gyp/16.14.0/deps/openssl/config -I/Users/taylor/.node-gyp/16.14.0/deps/openssl/openssl/include -I/Users/taylor/.node-gyp/16.14.0/deps/uv/include -I/Users/taylor/.node-gyp/16.14.0/deps/zlib -I/Users/taylor/.node-gyp/16.14.0/deps/v8/include -I../src/libsass/include  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp

-----
omitting a bunch of logs
----

npm ERR! 2 warnings generated.
npm ERR! In file included from ../src/binding.cpp:1:
npm ERR! In file included from ../../../../nan/nan.h:58:
npm ERR! In file included from /Users/taylor/.node-gyp/16.14.0/include/node/node.h:63:
npm ERR! In file included from /Users/taylor/.node-gyp/16.14.0/include/node/v8.h:30:
npm ERR! /Users/taylor/.node-gyp/16.14.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/taylor/workspace/static-timeline-generator/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node@16/16.14.0/bin/node" "/Users/taylor/workspace/static-timeline-generator/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/taylor/workspace/static-timeline-generator/node_modules/gulp-sass/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```
<details>

**Comment by taylorsilva** [comment]
It's 14. Install using node v14
